# Generated by Django 4.1.7 on 2023-10-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
